version: 2.1
# CI for cloudstate-samples/chat application
# DEPENDS ON Env variables   
# LB_BT_USERNAME typesafe-tools
# LB_BT_PASSCODE    xxxxxa5c
# LB_BT_REGISTRY lightbend-docker-registry.bintray.io
# LB_BT_CS_SAMPLES_REGISTRY cloudstate-samples

orbs:
  node: circleci/node@1.1.6

commands:
  install_protoc:
    description: "Install Protoc"
    parameters:
      version:
        type: string
        default: "3.11.2"
    steps:
      - run:
          name: "Install protoc"
          command: |
            mkdir -p /tmp/protoc
            cd /tmp/protoc
            wget https://github.com/protocolbuffers/protobuf/releases/download/v<< parameters.version >>/protoc-<< parameters.version >>-linux-x86_64.zip
            unzip protoc*.zip
            sudo mv bin/protoc /usr/local/bin/

jobs:
  docker-build:
    executor:
      name: node/default
      tag: '13.8.0'
    steps:
      - checkout
      - setup_remote_docker
      - install_protoc
      - node/with-cache:
          cache-key: chat/friends/package.json
          dir: chat/friends/node_modules/
          steps:
            - run:
                name: build friends docker image
                command: |
                  cd chat/friends
                  npm install
                  npm run prestart
                  docker build -t "$LB_BT_CS_SAMPLES_REGISTRY"/friends .
      - node/with-cache:
          cache-key: chat/presence/package.json
          dir: chat/presence/node_modules/
          steps:
            - run:
                name: build presence docker image
                command: |
                  cd chat/presence
                  npm install
                  npm run prestart
                  docker build -t "$LB_BT_CS_SAMPLES_REGISTRY"/presence .
      - node/with-cache:
          cache-key: chat/chat/package.json
          dir: chat/chat/node_modules/
          steps:
            - run:
                name: build chat docker image
                command: |
                  cd chat/chat
                  npm install
                  ./protogen.sh
                  npm run prestart
                  docker build -t "$LB_BT_CS_SAMPLES_REGISTRY"/chat .
      - node/with-cache:
          cache-key: shopping-cart/frontend/package.json
          dir: shopping-cart/frontend/node_modules/
          steps:
            - run:
                name: build shopping cart frontend docker image
                command: |
                  cd  shopping-cart/frontend/
                  npm install
                  ./protogen.sh
                  npm run prestart
                  npm run-script build
                  docker build -t "$LB_BT_CS_SAMPLES_REGISTRY"/frontend .
      - node/with-cache:
          cache-key: shopping-cart/js-shopping-cart/package.json
          dir: shopping-cart/js-shopping-cart/node_modules/
          steps:
            - run:
                name: build shopping cart docker image
                command: |
                  cd  shopping-cart/js-shopping-cart/
                  npm install
                  npm run prestart
                  docker build -t "$LB_BT_CS_SAMPLES_REGISTRY"/shopping-cart .
      - run:
          name: Archive Docker images
          command: |
             docker save -o images.tar  "$LB_BT_CS_SAMPLES_REGISTRY"/friends \
                                        "$LB_BT_CS_SAMPLES_REGISTRY"/presence \
                                        "$LB_BT_CS_SAMPLES_REGISTRY"/chat \
                                        "$LB_BT_CS_SAMPLES_REGISTRY"/frontend \
                                        "$LB_BT_CS_SAMPLES_REGISTRY"/shopping-cart
      - persist_to_workspace:
          root: .
          paths:
            - ./images.tar

  publish-to-registry:
    executor:
      name: node/default
      tag: '13.8.0'
    environment:
      DOCKER_IMAGE_TAG: latest
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: |
            docker load -i /tmp/workspace/images.tar
      - run:
          name: Publish Docker Images to BinTray
          command: |
            echo "$LB_BT_PASSCODE" | docker login -u "$LB_BT_USERNAME" --password-stdin "$LB_BT_REGISTRY"
            docker tag "$LB_BT_CS_SAMPLES_REGISTRY"/friends:latest "$LB_BT_REGISTRY/$LB_BT_CS_SAMPLES_REGISTRY"/friends:"$DOCKER_IMAGE_TAG"
            docker tag "$LB_BT_CS_SAMPLES_REGISTRY"/presence:latest "$LB_BT_REGISTRY/$LB_BT_CS_SAMPLES_REGISTRY"/presence:"$DOCKER_IMAGE_TAG"
            docker tag "$LB_BT_CS_SAMPLES_REGISTRY"/chat:latest "$LB_BT_REGISTRY/$LB_BT_CS_SAMPLES_REGISTRY"/chat:"$DOCKER_IMAGE_TAG"
            docker tag "$LB_BT_CS_SAMPLES_REGISTRY"/frontend:latest "$LB_BT_REGISTRY/$LB_BT_CS_SAMPLES_REGISTRY"/frontend:"$DOCKER_IMAGE_TAG"
            docker tag "$LB_BT_CS_SAMPLES_REGISTRY"/shopping-cart:latest "$LB_BT_REGISTRY/$LB_BT_CS_SAMPLES_REGISTRY"/shopping-cart:"$DOCKER_IMAGE_TAG"
            docker push "$LB_BT_REGISTRY/$LB_BT_CS_SAMPLES_REGISTRY"/friends:"$DOCKER_IMAGE_TAG"
            docker push "$LB_BT_REGISTRY/$LB_BT_CS_SAMPLES_REGISTRY"/presence:"$DOCKER_IMAGE_TAG"
            docker push "$LB_BT_REGISTRY/$LB_BT_CS_SAMPLES_REGISTRY"/chat:"$DOCKER_IMAGE_TAG"
            docker push "$LB_BT_REGISTRY/$LB_BT_CS_SAMPLES_REGISTRY"/frontend:"$DOCKER_IMAGE_TAG"
            docker push "$LB_BT_REGISTRY/$LB_BT_CS_SAMPLES_REGISTRY"/shopping-cart:"$DOCKER_IMAGE_TAG"

workflows:
  build_and_push:
    jobs:
      - docker-build
      - publish-to-registry:
          requires:
            - docker-build
          filters:
            branches:
              only: master
